export const PERSON_DETAILS_MODAL = 'PERSON_DETAILS_MODAL';
export const STARSHIP_DETAILS_MODAL = 'STARSHIP_DETAILS_MODAL';

export type ModalType = typeof PERSON_DETAILS_MODAL | typeof STARSHIP_DETAILS_MODAL;
